# coding: utf-8

"""
    OGC Compliant DX Resource Server

    OGC compliant Features and Common API definitions. Includes Schema and Response Objects.   <a href='/stac/api'>STAC API Documentation</a>    <a href='/metering/api'>DX Metering API Documentation</a>

    The version of the OpenAPI document: 1.0.1
    Contact: info@iudx.org.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransmissionMode(str, Enum):
    """
    TransmissionMode
    """

    """
    allowed enum values
    """
    VALUE = 'value'
    REFERENCE = 'reference'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransmissionMode from a JSON string"""
        return cls(json.loads(json_str))


