# flake8: noqa

# import apis into api package
from openapi_client.api.airports_api import AirportsApi
from openapi_client.api.coast_line_api import CoastLineApi
from openapi_client.api.digital_kiosk_locations_in_pimpri_chinchwad_city_api import DigitalKioskLocationsInPimpriChinchwadCityApi
from openapi_client.api.district_boundaries_corrected_api import DistrictBoundariesCorrectedApi
from openapi_client.api.district_headquarters_corrected_api import DistrictHeadquartersCorrectedApi
from openapi_client.api.ev_charging_station_locations_api import EVChargingStationLocationsApi
from openapi_client.api.features_api import FeaturesApi
from openapi_client.api.hospital_locations_in_kohima_city_api import HospitalLocationsInKohimaCityApi
from openapi_client.api.international_boundary_api import InternationalBoundaryApi
from openapi_client.api.lighthouse_locations_in_india_api import LighthouseLocationsInIndiaApi
from openapi_client.api.major_towns_api import MajorTownsApi
from openapi_client.api.mountain_pass_locations_in_india_api import MountainPassLocationsInIndiaApi
from openapi_client.api.national_roads_and_highways_api import NationalRoadsAndHighwaysApi
from openapi_client.api.other_site_locations_in_india_api import OtherSiteLocationsInIndiaApi
from openapi_client.api.railway_lines_api import RailwayLinesApi
from openapi_client.api.railway_station_points_api import RailwayStationPointsApi
from openapi_client.api.rivers_of_india_api import RiversOfIndiaApi
from openapi_client.api.smart_toilet_locations_in_ahmedabad_city_api import SmartToiletLocationsInAhmedabadCityApi
from openapi_client.api.state_boundaries_corrected_api import StateBoundariesCorrectedApi
from openapi_client.api.state_headquarters_api import StateHeadquartersApi
from openapi_client.api.subdistrict_boundaries_corrected_api import SubdistrictBoundariesCorrectedApi
from openapi_client.api.vmsb_locations_in_pimpri_chinchwad_city_api import VMSBLocationsInPimpriChinchwadCityApi
from openapi_client.api.vehicle_parking_facility_locations_in_chandigarh_api import VehicleParkingFacilityLocationsInChandigarhApi
from openapi_client.api.wi_fi_locations_in_pimpri_chinchwad_city_api import WiFiLocationsInPimpriChinchwadCityApi
from openapi_client.api.wildlife_sanctuary_locations_in_india_api import WildlifeSanctuaryLocationsInIndiaApi
from openapi_client.api.zoo_locations_in_india_api import ZooLocationsInIndiaApi

